### PR TITLE
Add virus scan service

### PR DESCRIPTION
**Pull request by pbolduc**
# Description

This PR includes the following proposed change(s):

- Adds virus scanning service

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by karahanb — APPROVED** [review]
Great work!

**Comment by pbolduc** [comment]
@karahanb heads up, I added client registration and configuration in this morning's commit. You may want to review this last change.

**Comment by karahanb** [comment]
> @karahanb heads up, I added client registration and configuration in this morning's commit. You may want to review this last change.

Thanks Phil, that looks good too. So we should be able to add the virus scan client into the workflow service like adding:
`builder.Services.AddVirusScanClient(builder.Configuration)` into Startup.cs and also define a `VirusScanConfiguration` class in workflow service with a `BaseUrl` property. Is that correct?

Maybe we should also add some details on the Readme file to explain how VirusScanClient should be configured for accessing.

**Review by karahanb — APPROVED** [review]

**Comment by pbolduc** [comment]
> So we should be able to add the virus scan client into the workflow service like adding: `builder.Services.AddVirusScanClient(builder.Configuration)` into Startup.cs and also define a `VirusScanConfiguration` class in workflow service with a `BaseUrl` property. Is that correct?

Yes this is correct. The only configuration parameter is the base url. It should be configured via VirusScan__BaseUrl environment variable.
 
> Maybe we should also add some details on the Readme file to explain how VirusScanClient should be configured for accessing.

True, this is missing.

**Pull request merged**
