### PR TITLE
TCVP-2492 update filters

### PR DESCRIPTION
**Pull request by Sharkww**
# Description

This PR includes the following proposed change(s):

- TCVP-2492
- update filters
- group filters to one file to have better management and cleaner codes
- filters will remains before users exit the app
- remove all loading screen block

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [x] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by KDNeufeld** [comment]
Probably some weird side effect of you working on the jjWorkbench for this PR, but it seems to have unintended side-effects on the staff workbench (DCF tab). The filters are not formatted correctly.

image

**Comment by KDNeufeld** [comment]
Can you add a validation error for the scenario where Date Submitted To: is before From: ?
image

**Comment by Sharkww** [comment]
@KDNeufeld fixed the first error

**Review by KDNeufeld — APPROVED** [review]
Thanks so much for your help with this. This is great.

**Pull request merged**
