### PR TITLE
Feature/tcvp 1215

### PR DESCRIPTION
**Pull request by lfdgov**
# Description

This PR includes the following proposed change(s):

- {List all the changes, if possible add the jira ticket #}

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [X] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pbolduc** [comment]
Probably should have rebased these changes off of main since there has been quite a few changes already merged into main since this branch was created.

**Comment by lfdgov** [comment]
> Probably should have rebased these changes off of main since there has been quite a few changes already merged into main since this branch was created.

I frequently merged main into my branch including immediately before pull request to get all the changes from main.

**Comment by lfdgov** [comment]
> 

does your comment refer to a change that i introduced or in general throughout the staff-portal or citizen-portal.  Are we assuming all times stored in db are in UTC?

**Comment by Sharkww** [comment]
> why do we parse the date as UTC? We dont know what time zone tickets are issued in. Check out this fiddle, the date is set to the 27th... http://jsfiddle.net/y7skzc1o/

I think this might be the code that I wrote in citizen portal, because it will be parsed as js date again, so we need to change the timezone to make it display correctly as local time

**Comment by pbolduc** [comment]
> > 
> 
> does your comment refer to a change that i introduced or in general throughout the staff-portal or citizen-portal. Are we assuming all times stored in db are in UTC?

No, but cause for tickets, we don't know the time zone. BC has 3 time zones:

- Pacific Standard Time
- Mountain Time
- Mountain Standard Time

**Comment by Sharkww** [comment]
We do not need to assume the timezone of the data. The Date that backend/OCR result passed to frontend should be a string in local timezone.

**Comment by Sharkww** [comment]
In addition, for js Date(dateData) will parse as local time zone. However, it will be displayed in UTC time in the html date input. So moment is working as reverse process to make it display correctly. If you need to pass the date time to the backend, you may need to use moment to do the reverse-reverse process.

**Comment by Sharkww** [comment]
The moment changes is because of TCVP-1133
https://github.com/bcgov/jag-traffic-courts-online/commit/7952bf5d81c4afdaef0f3a9e9f8ad4b189040671

Please keep it for now, otherwise it will cause display error. Thanks

**Review by Sharkww — APPROVED** [review]

**Pull request closed without merging**
