### PR TITLE
TCVP-2550 Added multiple search filters to Staff Workbench

### PR DESCRIPTION
**Pull request by KDNeufeld**
# Description

This PR includes the following proposed change(s):

TCVP-2550 Added Date Submitted, Ticket Number, Status, and Surname filters to Ticket Validation tab and Update Requests.
Cleaned up Update Requests so it looks better.

image

Note: as per existing design, these are only client-side filters, not search parameters.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Sharkww** [comment]
Is there any reasons for not using `mat-form-field` ?

**Comment by KDNeufeld** [comment]
> Is there any reasons for not using `mat-form-field` ?

Only that I don't know what that is. But I can research it and do that if that's better.

**Comment by Sharkww** [comment]
Ok, we had that package installed, you can use it freely. Please noted that we are using v14.

https://v14.material.angular.io/

**Comment by KDNeufeld** [comment]
> Ok, we had that package installed, you can use it freely. Please noted that we are using v14.
> 
> https://v14.material.angular.io/

Great. I updated the implementation to use mat-form-field instead. See updated screenshot.

**Comment by Sharkww** [comment]
And can you also change the button to use mat-button, so we can have less custom CSS. Thanks

**Comment by KDNeufeld** [comment]
> And can you also change the button to use mat-button, so we can have less custom CSS. Thanks

For sure. Done. But I'm pretty sure mat-button is not working correctly in staff-portal. The color="primary", color="accent", or color="warn" attributes don't work at all and the style looks nothing like the official BC Gov style.

This is the style we must follow:
https://bcgov.github.io/bootstrap-theme/docs/reference/simple/

The mat-button in staff-portal doesn't look like this so I still had to keep the custom css for now until this can be fixed globally.

**Review by Sharkww — APPROVED** [review]

**Pull request merged**
