### PR TITLE
Mock code table support

### PR DESCRIPTION
**Pull request by CarolCarpenterJustice**
# Description

This PR includes the following proposed change(s):

- Add support of mock code tables

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pbolduc — APPROVED** [review]
LGTM. I was just not sure what Jira task this relates to.

**Comment by rantifamilusi** [comment]
Code coverage is 60% on the total code, our target is 80%.

**Comment by CarolCarpenterJustice** [comment]
> Code coverage is 60% on the total code, our target is 80%.

Which code is it looking at for this statistic?

**Review by rantifamilusi — APPROVED** [review]
Looks good, we need to look out for code coverage in next PR

**Pull request merged**
