### PR TITLE
Renamed the 'oraface-api' to 'oracle-data-api' throughout the project…

### PR DESCRIPTION
**Pull request by karahanb**
… to keep the same naming convention as a standard

# Description

This PR includes the following proposed change(s):

- [TCVP-1255](https://justice.gov.bc.ca/jira/browse/TCVP-1255)
- Renamed the "oraface-api" to "oracle-data-api" throughout the project to keep the same naming convention as a standard.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [x] Yes
- [ ] No

If Yes: Has Docker been updated accordingly?

- [x] Yes
- [ ] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by KDNeufeld** [comment]
<artifactId>oracle-data-interface</artifactId> is still the old name

**Review by pbolduc — APPROVED** [review]
LGTM

**Comment by karahanb** [comment]
> `<artifactId>oracle-data-interface</artifactId>` is still the old name in pom.xml

Oh, sorry I missed that. Will update

**Review by KDNeufeld — APPROVED** [review]
LGTM

**Pull request merged**
